# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#Instrument.create({ name: "Basse 4 cordes" })
#Instrument.create({ name: "Basse 5 cordes" })
#Instrument.create({ name: "Batterie" })
#Instrument.create({ name: "Chant lead" })
#Instrument.create({ name: "Choeurs" })
#Instrument.create({ name: "Guitare 6 cordes" })
#Instrument.create({ name: "Guitare 7 cordes" })
#Instrument.create({ name: "Guitare 8 cordes" })
#Instrument.create({ name: "Keyboards" })
#Instrument.create({ name: "Lunières" })
#Instrument.create({ name: "Machines" })
#Instrument.create({ name: "Sonos" })

#puts "      💥"

#Genre.create({ name: 'Alternative' })
#Genre.create({ name: 'British' })
#Genre.create({ name: 'Electro rock' })
#Genre.create({ name: 'Electro punk' })
#Genre.create({ name: 'Emo' })
#Genre.create({ name: 'Fonk rock' })
#Genre.create({ name: 'Garage' })
#Genre.create({ name: 'Grunge' })
#Genre.create({ name: 'Hardcore' })
#Genre.create({ name: 'Indie' })
#Genre.create({ name: 'Mathcore' })
#Genre.create({ name: 'Mathrock' })
#Genre.create({ name: 'Melodic Hardcore' })
#Genre.create({ name: 'Metalcore' })
#Genre.create({ name: 'Noise' })
#Genre.create({ name: 'Pop rock' })
#Genre.create({ name: 'Pop punk' })
#Genre.create({ name: 'Post rock' })
#Genre.create({ name: 'Post punk' })
#Genre.create({ name: 'Punk' })
#Genre.create({ name: 'Rock' })
#Genre.create({ name: 'Rock n roll' })
#Genre.create({ name: 'Sreamo' })
#Genre.create({ name: 'Stoner' })
#Genre.create({ name: 'Surf rock' })

#puts "      💥"

#Ability.create({ name: 'Recording' })
#Ability.create({ name: 'Mix' })
#Ability.create({ name: 'Mastering' })
#Ability.create({ name: 'Music video making' })
#Ability.create({ name: 'Communication' })
#Ability.create({ name: 'Label' })
#Ability.create({ name: 'Sono live' })
#Ability.create({ name: 'Social Network' })
#Ability.create({ name: 'Radio' })
#Ability.create({ name: 'Photo' })
#Ability.create({ name: 'Association' })


  puts "      💥"


#Category.create({ name: 'Amateur' })
#Category.create({ name: 'Confirmed' })
#Category.create({ name: 'Semi Pro' })
#Category.create({ name: 'Professionnal' })

Region.create({ name: "01 - Ain" })
Region.create({ name: "02 - Aisne" })
Region.create({ name: "03 - Allier" })
Region.create({ name: "04 - Alpes-de-Haute-Provence" })
Region.create({ name: "05 - Hautes-alpes" })
Region.create({ name: "06 - Alpes-maritimes" })
Region.create({ name: "07 - Ardèche" })
Region.create({ name: "08 - Ardennes" })
Region.create({ name: "09 - Ariège" })
Region.create({ name: "10 - Aube" })
Region.create({ name: "11 - Aude" })
Region.create({ name: "12 - Aveyron" })
Region.create({ name: "13 - Bouches-du-Rhône" })
Region.create({ name: "14 - Calvados" })
Region.create({ name: "15 - Cantal" })
Region.create({ name: "16 - Charente" })
Region.create({ name: "17 - Charente-maritime" })
Region.create({ name: "18 - Cher" })
Region.create({ name: "19 - Corrèze" })
Region.create({ name: "2a - Corse-du-sud" })
Region.create({ name: "2b - Haute-Corse" })
Region.create({ name: "21 - Côte-d'Or" })
Region.create({ name: "22 - Côtes-d'Armor" })
Region.create({ name: "23 - Creuse" })
Region.create({ name: "24 - Dordogne" })
Region.create({ name: "25 - Doubs" })
Region.create({ name: "26 - Drôme" })
Region.create({ name: "27 - Eure" })
Region.create({ name: "28 - Eure-et-loir" })
Region.create({ name: "29 - Finistère" })
Region.create({ name: "30 - Gard" })
Region.create({ name: "31 - Haute-garonne" })
Region.create({ name: "32 - Gers" })
Region.create({ name: "33 - Gironde" })
Region.create({ name: "34 - Hérault" })
Region.create({ name: "35 - Ille-et-vilaine" })
Region.create({ name: "36 - Indre" })
Region.create({ name: "37 - Indre-et-loire" })
Region.create({ name: "38 - Isère" })
Region.create({ name: "39 - Jura" })
Region.create({ name: "40 - Landes" })
Region.create({ name: "41 - Loir-et-cher" })
Region.create({ name: "42 - Loire" })
Region.create({ name: "43 - Haute-loire" })
Region.create({ name: "44 - Loire-atlantique" })
Region.create({ name: "45 - Loiret" })
Region.create({ name: "46 - Lot" })
Region.create({ name: "47 - Lot-et-garonne" })
Region.create({ name: "48 - Lozère" })
Region.create({ name: "49 - Maine-et-loire" })
Region.create({ name: "50 - Manche" })
Region.create({ name: "51 - Marne" })
Region.create({ name: "52 - Haute-marne" })
Region.create({ name: "53 - Mayenne" })
Region.create({ name: "54 - Meurthe-et-moselle" })
Region.create({ name: "55 - Meuse" })
Region.create({ name: "56 - Morbihan" })
Region.create({ name: "57 - Moselle" })
Region.create({ name: "58 - Nièvre" })
Region.create({ name: "59 - Nord" })
Region.create({ name: "60 - Oise" })
Region.create({ name: "61 - Orne" })
Region.create({ name: "62 - Pas-de-calais" })
Region.create({ name: "63 - Puy-de-dôme" })
Region.create({ name: "64 - Pyrénées-atlantiques" })
Region.create({ name: "65 - Hautes-Pyrénées" })
Region.create({ name: "66 - Pyrénées-orientales" })
Region.create({ name: "67 - Bas-rhin" })
Region.create({ name: "68 - Haut-rhin" })
Region.create({ name: "69 - Rhône" })
Region.create({ name: "70 - Haute-saône" })
Region.create({ name: "71 - Saône-et-loire" })
Region.create({ name: "72 - Sarthe" })
Region.create({ name: "73 - Savoie" })
Region.create({ name: "74 - Haute-savoie" })
Region.create({ name: "75 - Paris" })
Region.create({ name: "76 - Seine-maritime" })
Region.create({ name: "77 - Seine-et-marne" })
Region.create({ name: "78 - Yvelines" })
Region.create({ name: "79 - Deux-sèvres" })
Region.create({ name: "80 - Somme" })
Region.create({ name: "81 - Tarn" })
Region.create({ name: "82 - Tarn-et-garonne" })
Region.create({ name: "83 - Var" })
Region.create({ name: "84 - Vaucluse" })
Region.create({ name: "85 - Vendée" })
Region.create({ name: "86 - Vienne" })
Region.create({ name: "87 - Haute-vienne" })
Region.create({ name: "88 - Vosges" })
Region.create({ name: "89 - Yonne" })
Region.create({ name: "90 - Territoire de belfort" })
Region.create({ name: "91 - Essonne" })
Region.create({ name: "92 - Hauts-de-seine" })
Region.create({ name: "93 - Seine-Saint-Denis" })
Region.create({ name: "94 - Val-de-marne" })
Region.create({ name: "95 - Val-d'oise" })

  puts "      💥"

